version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/packages/*'
    schedule:
      interval: 'weekly'
    groups:
      patches:
        update-types:
          - 'patch'

  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'daily'
