// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: agoric/types/stream.proto

package stream

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EndState is the state of the stream at the last position in this cell.
type StreamCell_EndState int32

const (
	// END_STATE_UNSPECIFIED means unknown end state.
	StreamCell_END_STATE_UNSPECIFIED StreamCell_EndState = 0
	// END_STATE_APPENDABLE means that appending to this cell is possible.
	StreamCell_END_STATE_APPENDABLE StreamCell_EndState = 1
	// END_STATE_FINISHED means this cell has terminated.
	StreamCell_END_STATE_FINISHED StreamCell_EndState = 2
	// END_STATE_FAILURE means this cell has terminated with an error value.
	StreamCell_END_STATE_FAILURE StreamCell_EndState = 3
)

var StreamCell_EndState_name = map[int32]string{
	0: "END_STATE_UNSPECIFIED",
	1: "END_STATE_APPENDABLE",
	2: "END_STATE_FINISHED",
	3: "END_STATE_FAILURE",
}

var StreamCell_EndState_value = map[string]int32{
	"END_STATE_UNSPECIFIED": 0,
	"END_STATE_APPENDABLE":  1,
	"END_STATE_FINISHED":    2,
	"END_STATE_FAILURE":     3,
}

func (x StreamCell_EndState) String() string {
	return proto.EnumName(StreamCell_EndState_name, int32(x))
}

func (StreamCell_EndState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bf761c79ece967d, []int{0, 0}
}

// StreamCell represents one publish state in a vstream stream.
type StreamCell struct {
	// Chronologically-ordered list of values for this cell.
	// If state=END_STATE_FAILURE, the last value is the serialised error.
	Values [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	// The block height in which this cell was last updated.
	UpdatedBlockHeight int64 `protobuf:"varint,2,opt,name=updated_block_height,json=updatedBlockHeight,proto3" json:"updated_block_height" yaml:"updated_block_height"`
	// The first value's sequence number.  0 means unspecified
	FirstSequenceNumber uint64 `protobuf:"varint,3,opt,name=first_sequence_number,json=firstSequenceNumber,proto3" json:"first_sequence_number" yaml:"first_sequence_number"`
	// The state as of the last value.
	EndState StreamCell_EndState `protobuf:"varint,4,opt,name=end_state,json=endState,proto3,enum=agoric.types.StreamCell_EndState" json:"end_state" yaml:"end_state"`
	// The prior position in the stream.
	Prior StreamPosition `protobuf:"bytes,5,opt,name=prior,proto3" json:"prior"`
}

func (m *StreamCell) Reset()         { *m = StreamCell{} }
func (m *StreamCell) String() string { return proto.CompactTextString(m) }
func (*StreamCell) ProtoMessage()    {}
func (*StreamCell) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bf761c79ece967d, []int{0}
}
func (m *StreamCell) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StreamCell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StreamCell.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StreamCell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamCell.Merge(m, src)
}
func (m *StreamCell) XXX_Size() int {
	return m.Size()
}
func (m *StreamCell) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamCell.DiscardUnknown(m)
}

var xxx_messageInfo_StreamCell proto.InternalMessageInfo

func (m *StreamCell) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *StreamCell) GetUpdatedBlockHeight() int64 {
	if m != nil {
		return m.UpdatedBlockHeight
	}
	return 0
}

func (m *StreamCell) GetFirstSequenceNumber() uint64 {
	if m != nil {
		return m.FirstSequenceNumber
	}
	return 0
}

func (m *StreamCell) GetEndState() StreamCell_EndState {
	if m != nil {
		return m.EndState
	}
	return StreamCell_END_STATE_UNSPECIFIED
}

func (m *StreamCell) GetPrior() StreamPosition {
	if m != nil {
		return m.Prior
	}
	return StreamPosition{}
}

// StreamPosition is data that refers to a particular stream cell value.
type StreamPosition struct {
	// The height at which the cell is stored.
	BlockHeight int64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height" yaml:"block_height"`
	// The store name under which the cell is stored.
	StoreName string `protobuf:"bytes,2,opt,name=store_name,json=storeName,proto3" json:"store_name" yaml:"store_name"`
	// The subkey under which the cell is stored.
	StoreSubkey []byte `protobuf:"bytes,3,opt,name=store_subkey,json=storeSubkey,proto3" json:"store_subkey" yaml:"store_subkey"`
	// The sequence number of the value at this position.
	SequenceNumber uint64 `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"value_offset" yaml:"value_offset"`
}

func (m *StreamPosition) Reset()         { *m = StreamPosition{} }
func (m *StreamPosition) String() string { return proto.CompactTextString(m) }
func (*StreamPosition) ProtoMessage()    {}
func (*StreamPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bf761c79ece967d, []int{1}
}
func (m *StreamPosition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StreamPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StreamPosition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StreamPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamPosition.Merge(m, src)
}
func (m *StreamPosition) XXX_Size() int {
	return m.Size()
}
func (m *StreamPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamPosition.DiscardUnknown(m)
}

var xxx_messageInfo_StreamPosition proto.InternalMessageInfo

func (m *StreamPosition) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *StreamPosition) GetStoreName() string {
	if m != nil {
		return m.StoreName
	}
	return ""
}

func (m *StreamPosition) GetStoreSubkey() []byte {
	if m != nil {
		return m.StoreSubkey
	}
	return nil
}

func (m *StreamPosition) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func init() {
	proto.RegisterEnum("agoric.types.StreamCell_EndState", StreamCell_EndState_name, StreamCell_EndState_value)
	proto.RegisterType((*StreamCell)(nil), "agoric.types.StreamCell")
	proto.RegisterType((*StreamPosition)(nil), "agoric.types.StreamPosition")
}

func init() { proto.RegisterFile("agoric/types/stream.proto", fileDescriptor_2bf761c79ece967d) }

var fileDescriptor_2bf761c79ece967d = []byte{
	// 575 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x31, 0x6f, 0x9b, 0x40,
	0x14, 0xc7, 0x21, 0x26, 0x51, 0x7c, 0xb6, 0x5c, 0xe7, 0x62, 0x47, 0xa4, 0x8d, 0xc0, 0xa1, 0x43,
	0xbd, 0x14, 0xa4, 0x74, 0x48, 0x9b, 0xcd, 0xc4, 0x44, 0x71, 0x15, 0x21, 0x17, 0x92, 0xa5, 0x0b,
	0x02, 0xfb, 0x8c, 0x91, 0x81, 0x73, 0x39, 0xa8, 0xe4, 0x6f, 0xd1, 0x7e, 0x83, 0x7e, 0x92, 0xce,
	0x19, 0x33, 0x76, 0x42, 0x95, 0xbd, 0x54, 0x1e, 0xfd, 0x09, 0x2a, 0x1f, 0x6e, 0xc1, 0x91, 0x37,
	0xde, 0xef, 0xff, 0xee, 0xee, 0xf1, 0xde, 0xff, 0x81, 0x53, 0xdb, 0xc5, 0x91, 0x37, 0x50, 0xe2,
	0xd9, 0x14, 0x11, 0x85, 0xc4, 0x11, 0xb2, 0x03, 0x79, 0x1a, 0xe1, 0x18, 0xc3, 0x6a, 0x26, 0xc9,
	0x54, 0x7a, 0xd9, 0x70, 0xb1, 0x8b, 0xa9, 0xa0, 0xac, 0xbf, 0xb2, 0x1c, 0xe9, 0x3b, 0x07, 0x80,
	0x49, 0x0f, 0x5d, 0x23, 0xdf, 0x87, 0x27, 0xe0, 0xe0, 0xab, 0xed, 0x27, 0x88, 0xf0, 0x6c, 0xab,
	0xd4, 0xae, 0x1a, 0x9b, 0x08, 0x7a, 0xa0, 0x91, 0x4c, 0x87, 0x76, 0x8c, 0x86, 0x96, 0xe3, 0xe3,
	0xc1, 0xc4, 0x1a, 0x23, 0xcf, 0x1d, 0xc7, 0xfc, 0x5e, 0x8b, 0x6d, 0x97, 0xd4, 0xcb, 0x65, 0x2a,
	0xee, 0xd4, 0x57, 0xa9, 0xf8, 0x6a, 0x66, 0x07, 0xfe, 0x95, 0xb4, 0x4b, 0x95, 0x0c, 0xb8, 0xc1,
	0xea, 0x9a, 0xde, 0x52, 0x08, 0x03, 0xd0, 0x1c, 0x79, 0x11, 0x89, 0x2d, 0x82, 0xbe, 0x24, 0x28,
	0x1c, 0x20, 0x2b, 0x4c, 0x02, 0x07, 0x45, 0x7c, 0xa9, 0xc5, 0xb6, 0x39, 0xf5, 0xc3, 0x32, 0x15,
	0x77, 0x27, 0xac, 0x52, 0xf1, 0x2c, 0x7b, 0x6c, 0xa7, 0x2c, 0x19, 0xc7, 0x94, 0x9b, 0x1b, 0xac,
	0x53, 0x0a, 0x6d, 0x50, 0x46, 0xe1, 0xd0, 0x22, 0xb1, 0x1d, 0x23, 0x9e, 0x6b, 0xb1, 0xed, 0xda,
	0xc5, 0xb9, 0x5c, 0x6c, 0x9c, 0x9c, 0xb7, 0x47, 0xd6, 0xc2, 0xa1, 0xb9, 0x4e, 0x54, 0xcf, 0x97,
	0xa9, 0x98, 0x9f, 0x5b, 0xa5, 0x62, 0x3d, 0x7b, 0xf9, 0x3f, 0x92, 0x8c, 0x43, 0xb4, 0x49, 0x86,
	0xef, 0xc1, 0xfe, 0x34, 0xf2, 0x70, 0xc4, 0xef, 0xb7, 0xd8, 0x76, 0xe5, 0xe2, 0x6c, 0xd7, 0xf5,
	0x7d, 0x4c, 0xbc, 0xd8, 0xc3, 0xa1, 0xca, 0x3d, 0xa6, 0x22, 0x63, 0x64, 0x07, 0xa4, 0x10, 0x1c,
	0xfe, 0x7b, 0x12, 0x9e, 0x82, 0xa6, 0xa6, 0x77, 0x2d, 0xf3, 0xbe, 0x73, 0xaf, 0x59, 0x0f, 0xba,
	0xd9, 0xd7, 0xae, 0x7b, 0x37, 0x3d, 0xad, 0x5b, 0x67, 0x20, 0x0f, 0x1a, 0xb9, 0xd4, 0xe9, 0xf7,
	0x35, 0xbd, 0xdb, 0x51, 0xef, 0xb4, 0x3a, 0x0b, 0x4f, 0x00, 0xcc, 0x95, 0x9b, 0x9e, 0xde, 0x33,
	0x6f, 0xb5, 0x6e, 0x7d, 0x0f, 0x36, 0xc1, 0x51, 0x81, 0x77, 0x7a, 0x77, 0x0f, 0x86, 0x56, 0x2f,
	0x5d, 0x71, 0x7f, 0x7e, 0x88, 0x8c, 0xf4, 0x73, 0x0f, 0xd4, 0xb6, 0xab, 0x82, 0x1f, 0x41, 0x75,
	0x6b, 0xee, 0x2c, 0x9d, 0xfb, 0x9b, 0x65, 0x2a, 0x56, 0x9f, 0xcd, 0xfb, 0x38, 0x6b, 0xc4, 0xf6,
	0x9c, 0x2b, 0x4e, 0x61, 0xc0, 0x2a, 0x00, 0x24, 0xc6, 0x11, 0xb2, 0x42, 0x3b, 0x40, 0xd4, 0x41,
	0x65, 0xf5, 0xf5, 0x32, 0x15, 0x0b, 0x74, 0x95, 0x8a, 0x47, 0xd9, 0x3d, 0x39, 0x93, 0x8c, 0x32,
	0x0d, 0x74, 0x3b, 0x40, 0xeb, 0x7a, 0x32, 0x85, 0x24, 0xce, 0x04, 0xcd, 0xa8, 0x37, 0xaa, 0x59,
	0x3d, 0x45, 0x9e, 0xd7, 0x53, 0xa4, 0x92, 0x51, 0xa1, 0xa1, 0x49, 0x23, 0xd8, 0x07, 0x2f, 0x9e,
	0x5b, 0x8d, 0xa3, 0x56, 0xa3, 0xd7, 0xd1, 0x05, 0xb0, 0xf0, 0x68, 0x44, 0x50, 0xe1, 0xf7, 0x8a,
	0x54, 0x32, 0x6a, 0x64, 0xcb, 0x53, 0xea, 0xa7, 0xc7, 0xb9, 0xc0, 0x3e, 0xcd, 0x05, 0xf6, 0xf7,
	0x5c, 0x60, 0xbf, 0x2d, 0x04, 0xe6, 0x69, 0x21, 0x30, 0xbf, 0x16, 0x02, 0xf3, 0xf9, 0xd2, 0xf5,
	0xe2, 0x71, 0xe2, 0xc8, 0x03, 0x1c, 0x28, 0x9d, 0x6c, 0x71, 0x33, 0x33, 0xbc, 0x25, 0xc3, 0x89,
	0xe2, 0x62, 0xdf, 0x0e, 0x5d, 0x65, 0x80, 0x49, 0x80, 0xc9, 0xd6, 0x46, 0x3b, 0x07, 0x74, 0x5d,
	0xdf, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xca, 0xc4, 0x8f, 0xa2, 0xef, 0x03, 0x00, 0x00,
}

func (m *StreamCell) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StreamCell) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StreamCell) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Prior.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintStream(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.EndState != 0 {
		i = encodeVarintStream(dAtA, i, uint64(m.EndState))
		i--
		dAtA[i] = 0x20
	}
	if m.FirstSequenceNumber != 0 {
		i = encodeVarintStream(dAtA, i, uint64(m.FirstSequenceNumber))
		i--
		dAtA[i] = 0x18
	}
	if m.UpdatedBlockHeight != 0 {
		i = encodeVarintStream(dAtA, i, uint64(m.UpdatedBlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Values) > 0 {
		for iNdEx := len(m.Values) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Values[iNdEx])
			copy(dAtA[i:], m.Values[iNdEx])
			i = encodeVarintStream(dAtA, i, uint64(len(m.Values[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *StreamPosition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StreamPosition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StreamPosition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SequenceNumber != 0 {
		i = encodeVarintStream(dAtA, i, uint64(m.SequenceNumber))
		i--
		dAtA[i] = 0x20
	}
	if len(m.StoreSubkey) > 0 {
		i -= len(m.StoreSubkey)
		copy(dAtA[i:], m.StoreSubkey)
		i = encodeVarintStream(dAtA, i, uint64(len(m.StoreSubkey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.StoreName) > 0 {
		i -= len(m.StoreName)
		copy(dAtA[i:], m.StoreName)
		i = encodeVarintStream(dAtA, i, uint64(len(m.StoreName)))
		i--
		dAtA[i] = 0x12
	}
	if m.BlockHeight != 0 {
		i = encodeVarintStream(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintStream(dAtA []byte, offset int, v uint64) int {
	offset -= sovStream(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StreamCell) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Values) > 0 {
		for _, b := range m.Values {
			l = len(b)
			n += 1 + l + sovStream(uint64(l))
		}
	}
	if m.UpdatedBlockHeight != 0 {
		n += 1 + sovStream(uint64(m.UpdatedBlockHeight))
	}
	if m.FirstSequenceNumber != 0 {
		n += 1 + sovStream(uint64(m.FirstSequenceNumber))
	}
	if m.EndState != 0 {
		n += 1 + sovStream(uint64(m.EndState))
	}
	l = m.Prior.Size()
	n += 1 + l + sovStream(uint64(l))
	return n
}

func (m *StreamPosition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovStream(uint64(m.BlockHeight))
	}
	l = len(m.StoreName)
	if l > 0 {
		n += 1 + l + sovStream(uint64(l))
	}
	l = len(m.StoreSubkey)
	if l > 0 {
		n += 1 + l + sovStream(uint64(l))
	}
	if m.SequenceNumber != 0 {
		n += 1 + sovStream(uint64(m.SequenceNumber))
	}
	return n
}

func sovStream(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStream(x uint64) (n int) {
	return sovStream(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StreamCell) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStream
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StreamCell: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StreamCell: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Values", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Values = append(m.Values, make([]byte, postIndex-iNdEx))
			copy(m.Values[len(m.Values)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedBlockHeight", wireType)
			}
			m.UpdatedBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstSequenceNumber", wireType)
			}
			m.FirstSequenceNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FirstSequenceNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndState", wireType)
			}
			m.EndState = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndState |= StreamCell_EndState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prior", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Prior.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStream(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StreamPosition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStream
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StreamPosition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StreamPosition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoreName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreSubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoreSubkey = append(m.StoreSubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.StoreSubkey == nil {
				m.StoreSubkey = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SequenceNumber", wireType)
			}
			m.SequenceNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SequenceNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStream(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStream(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStream
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStream
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStream
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStream
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStream
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStream
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStream        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStream          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStream = fmt.Errorf("proto: unexpected end of group")
)
