name: Chain deployment test

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  deployment-test:
    runs-on: ubuntu-18.04 # trusty
    steps:
    - uses: actions/checkout@v2
      with:
        clean: 'false'
    - uses: ./.github/actions/restore-golang
      with:
        go-version: 1.15
    - uses: ./.github/actions/restore-node
      with:
        node-version: 14.x
    - name: Build cosmic-swingset dependencies
      run: |
        # Some of our build relies on /usr/src/agoric-sdk
        set -e
        sudo mv "$GITHUB_WORKSPACE" /usr/src/agoric-sdk
        ln -s /usr/src/agoric-sdk "$GITHUB_WORKSPACE"
        cd /usr/src/agoric-sdk/packages/cosmic-swingset
        make install
      working-directory: /
    - run: sudo ./packages/deployment/scripts/install-deps.sh
      working-directory: /usr/src/agoric-sdk
    - run: /usr/src/agoric-sdk/packages/deployment/scripts/integration-test.sh
      working-directory: ~
      env:
        NETWORK_NAME: chaintest
